### ISSUE TITLE
Helpful, comprehensive version for Obj-C. Swift plans?

### ISSUE THREAD

**Issue by zallanx** [twilio/ip-demo-ios#20]
This is a great project that showcases super well the capabilities of the Twilio Chat SDK. I was wondering if a Swift 3 version is coming?

There were previous blog posts that built upon a Swift project (https://www.twilio.com/blog/2015/12/designing-chat-applications-for-ios-using-swift.html), but it uses old Swift 2 syntax is now run into compile errors. I think a Swift version of this comprehensive demo would be super helpful.

**Comment by rbeiter** [comment]
Hi zallanx,

A swift version of the demo app is definitely something on our roadmap but I don't have a date to share at this time.  We'll update you when we have this available and appreciate the feedback that the existing Objective-C version has been helpful to you!

Thank you,
Randy

**Comment by zallanx** [comment]
Thanks Randy. I look forward to it.

**Comment by webwarrior06** [comment]
Really needed :(

**Comment by berkus** [comment]
A new version of the demo app with all the bells and whistles is in the works, no ETA but we plan to release it as soon as it's ready.

**Comment by jigar007** [comment]
@berkus Any update on a swift version of chat app demo?

**Comment by berkus** [comment]
@jigar007 it's in production but not released yet.

**Comment by jigar007** [comment]
@berkus Do you know when it will release?

As I'm using Twilio messaging API in production and I'm getting a few issues with media.

Actually, I am looking for caching mechanism recommended in Twillio documentation at https://www.twilio.com/docs/chat/media-support?code-sample=code-creating-a-media-message-2&code-language=Swift&code-sdk-version=default

![image](https://user-images.githubusercontent.com/9298974/83531610-9086fb80-a530-11ea-92f2-f9b857a94f2b.png)

**Comment by berkus** [comment]
@jigar007 well, just save the media by its mediaSid into any sort of local storage and first fetch it from there before going for download. mediaSids are unique so you will either already have it cached or download and cache it.

**Comment by berkus** [comment]
For the Swift demo app I don't have any time lines at the moment.

**Comment by jigar007** [comment]
@berkus No worries, thanks but I'll just store images manually at the moment.

**Comment by metizror** [comment]
Any Updates on Swift Version?

**Comment by Gray-Wind** [comment]
Yes, we are planning to publish the new demo application soon.

**Comment by berkus** [comment]
Hi all, the Swift demo app for Conversations is published [here](https://github.com/twilio/twilio-conversations-demo-swift).
