### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Mani101991** [twilio/ip-demo-ios#27]
Hello Twillo Team,

The Demo App is not running. So many errors came in the demo application. Please fix this ASAP

**Comment by rbeiter** [comment]
Hello @Mani101991,

Have you run `pod install` if you are using CocoaPods or followed the instructions [here](https://www.twilio.com/docs/api/chat/sdks#ios-sdk) if integrating manually?  The project is building fine for me.

Thank you,
Randy

**Comment by Mani101991** [comment]
Hello Randy,

I was already installed frameworks via pod. But Error Came. Please check it once again.

**Comment by rbeiter** [comment]
Hi Mani,

I just pulled the project, install the pods and compiled the project.  The only error that appeared for me is the #error directive we have in the project where you are expected to put in your auth token.

Can you please post a log of the errors you are seeing so we can look into them?

Thank you,
Randy

**Comment by Mani101991** [comment]
Hello Randy,
Semantic issue and ARC Semantic issues is Appear. 
![screen shot 2017-11-02 at 5 08 51 pm](https://user-images.githubusercontent.com/31679116/32324197-9521535c-bff0-11e7-9c9d-4a338a532298.png)


Xcode 8.1 i am using. Please check

**Comment by Mani101991** [comment]
Hello Randy,

From Github kindly download the source instead of pulling the source and check. Please fix this ASAP

**Comment by rbeiter** [comment]
Hi Mani,

Since it's only the media related methods causing an error, it seems like Chat 2.0.0 is not being used but an earlier version (1.x).  Have you run `pod repo update` and `pod install` to ensure the pods are up to date?  Is it possible you updated the chat demo application from a previous version of the demo without running `pod install` again?  Your `Podfile.lock` should indicate the version of the framework in use, it should be at least 2.0.0 if you are using the master branch of the demo application.

Thank you,
Randy

**Comment by rbeiter** [comment]
> From Github kindly download the source instead of pulling the source and check. Please fix this ASAP

The test I performed within the last hour was to:
- download https://github.com/twilio/twilio-chat-demo-ios/archive/master.zip
- unzip the archive to a completely new clean directory
- run `pod install`
- open the xcworkspace
- build the project

This worked as expected.  Have you also tried to a brand new folder not used previously?

**Comment by Mani101991** [comment]
Hi Randy,

i have downloaded the project and new directory to put it for project. i was trying to install pod install. But this below error came. Please check attached screenshots

![screen shot 2017-11-02 at 5 53 07 pm](https://user-images.githubusercontent.com/31679116/32325938-0083ea46-bff7-11e7-8c20-129aac9ec9c9.png)

**Comment by Mani101991** [comment]
Hi Randy,

I have downloaded the project using you mentioned that link, and unzip the link to put it the new directory to project, and open the terminal, just entered pod install. But this error came below. Please check and reply, I have attached screenshots.

![screen shot 2017-11-02 at 5 53 07 pm](https://user-images.githubusercontent.com/31679116/32326143-bc0e7dbc-bff7-11e7-93e5-e3aa546d9b96.png)

**Comment by Mani101991** [comment]
HI Randy,

Are you checked it above comments?. Please reply

**Comment by rbeiter** [comment]
Hi Mani,

Given the error in the screenshot above, it looks like `TwilioAccessManager` is not known to cococapods on your system.  Can you try running `pod repo update` then `pod install` again to see if it helps the issue?

Thank you,
Randy

**Comment by Mani101991** [comment]
ok thank you so much rbeiter. i will check and let you know.

**Comment by rbeiter** [comment]
Hi Mani,

Just reaching out to see if this solved the errors you were seeing?

Thank you,
Randy

**Comment by Mani101991** [comment]
Hi Randy,
 The Source is successfully running. i created a token, when i use the token it show as 

> error received: Error Domain=signal.sdk.domain.error Code=102 "Error validating token." UserInfo={kTCHErrorMsgKey=Error validating token., NSLocalizedDescription=Error validating token.}

Please reply me randy

**Comment by rbeiter** [comment]
Hi Mani,

I'm glad the demo project is working for you now!  For token related issues, it will be helpful to be able to link your inquiry with your account so we can help you better.  May I ask you reach out to Twilio support on this page so we can help you further?  https://www.twilio.com/help/contact

Thank you,
Randy

**Comment by rbeiter** [comment]
Going to close this issue, please reach out if we can help you further.
