### ISSUE TITLE
Channel available through channelsList()?.channel(withSidOrUniqueName) after it was deleted

### ISSUE THREAD

**Issue by stefanluptak** [twilio/ip-demo-ios#31]
Hi, it's me again. :-)

When I do `channel.destroy()`, then wait for the `func chatClient(_ client: TwilioChatClient, channelDeleted channel: TCHChannel)` delegated method and then call `channelsList()?.channel(withSidOrUniqueName: <THAT_CHANNEL_UNIQUENAME>)`, I am getting `result.isSuccesfull()` equal `true` and even the `channel` argument of the completion is available.

Am I doing something wrong? I would assume that the channel won't be available after it's deleted.

BTW: Is this the correct way to discuss things like this?

Thanks, Stefan.

**Comment by josefrichter** [comment]
I don't know, my guess is that it takes Twilio some time to sync things on their side. Do we need the `false` response in real time?

**Comment by josefrichter** [comment]
I'll just add that our use case is this: we create a "secret" channel for communication between two users and we need to close and delete it after the communication ends. To wipe the whole history. But the same two users can initiate another "secret" conversation within minutes. So we need to create the channel again. But we can't because it says the channel still exists, but it cannot be joined anymore.

**Comment by rbeiter** [comment]
Hi @josefrichter  and @EskiMag ,

My apologies for the delay in response.  This is a bug in the client where the deleted channel is still cached locally after deletion from the server.  Operations against it will fail but the object will still be returned.

A fix for this is coming soon but in the meantime one work-around I can recommend is before destroying the channel, nil out the unique name of the channel.  This will free it up in the local client for subsequent communications between the two users.

I'll update this issue when the new release is available.

To answer @EskiMag 's question, you can also contact Twilio support on items like this via https://support.twilio.com/hc/en-us/requests/new . while we monitor venues such as issues here and StackOverflow, support is typically the most direct path to reach out.

Thank you,
Randy

**Comment by stefanluptak** [comment]
Hi @rbeiter, I saw Twilio Programmable Chat SDK for iOS is now available as 2.2.0. (https://www.twilio.com/docs/api/chat/changelogs/ios) Is this bug fixed there?

**Comment by rbeiter** [comment]
Hi @EskiMag,

2.2.0 should indeed address this issue for you.

Thank you,
Randy

**Comment by rbeiter** [comment]
Closing this for now.  Please reach out to us again if 2.2.0 does not resolve this issue for you.

Thank you,
Randy
