### ISSUE TITLE
TwilioChatClient Memory leak

### ISSUE THREAD

**Issue by serjooo** [twilio/ip-demo-ios#33]
Hello! I translated the `ChatManager` from Objective-c to Swift the code could be found here:
https://gist.github.com/serjooo/c26904b460584ff4bbb1c0a8352717ab

And I noticed that after I `shutdown()` and clear the `TwilioChatClient`, there are some objects in the `TwilioChatClient` that leak. Here are screenshots of what is leaking

![screen shot 2017-12-20 at 3 33 30 pm](https://user-images.githubusercontent.com/7988482/34209604-7f857d22-e59b-11e7-92e7-858386efd025.png)
![screen shot 2017-12-20 at 3 33 41 pm](https://user-images.githubusercontent.com/7988482/34209609-81e4afde-e59b-11e7-9ef7-4711d9a8d63d.png)
![screen shot 2017-12-20 at 3 33 57 pm](https://user-images.githubusercontent.com/7988482/34209611-8447af6a-e59b-11e7-9b3f-61a4828f5f1a.png)
![screen shot 2017-12-20 at 3 34 13 pm](https://user-images.githubusercontent.com/7988482/34209613-86ced948-e59b-11e7-87a5-bf949d7f152b.png)
![screen shot 2017-12-20 at 3 34 22 pm](https://user-images.githubusercontent.com/7988482/34209616-898e314c-e59b-11e7-8120-efb462da7f6e.png)

I thought it might have been that I have done something wrong. I tested the Obj-c Demo and I noticed the same problem after logging out.

**Comment by rbeiter** [comment]
Hi @serjooo,

Just wanted to let you know we've investigated the above and found a leak that will be addressed in a future SDK release.

Thank you,
Randy

**Comment by berkus** [comment]
These leaks should have been fixed already, closing.
