### ISSUE TITLE
Many crashes in Crashlytics  EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x0000000102dce7c0

### ISSUE THREAD

**Issue by perlasivakrishna** [twilio/ip-demo-ios#39]
[com.sendaride.carepartner_issue_92_crash_8ca398dbdbfe45d68e0515b8be5fefcf_DNE_0_v2.txt](https://github.com/twilio/twilio-chat-demo-ios/files/2079215/com.sendaride.carepartner_issue_92_crash_8ca398dbdbfe45d68e0515b8be5fefcf_DNE_0_v2.txt)
I'm using latest SDK version. But Im getting many crashes. Im not sure when its happening. Im attaching all the crash reports. please check.  As I reported previously [Old crash](https://github.com/twilio/cocoapod-specs/issues/124#issuecomment-362585148) Im calling Shutdown in application terminate method. 

func applicationWillTerminate(_ application: UIApplication) {
        MessagingManager.sharedManager().client?.shutdown()
        MessagingManager.sharedManager().client = nil
    }

[com.sendaride.carepartner_issue_92_crash_e727a9b06950480cbb531fddc63362da_DNE_0_v2.txt](https://github.com/twilio/twilio-chat-demo-ios/files/2075215/com.sendaride.carepartner_issue_92_crash_e727a9b06950480cbb531fddc63362da_DNE_0_v2.txt)
[com.sendaride.carepartner_issue_97_crash_9f3cc97a8b584f52888f26cd962145a6_DNE_0_v2.txt](https://github.com/twilio/twilio-chat-demo-ios/files/2075216/com.sendaride.carepartner_issue_97_crash_9f3cc97a8b584f52888f26cd962145a6_DNE_0_v2.txt)
[com.sendaride.carepartner_issue_99_crash_e5ff8148156c4bdbbc3f1411fefa09ce_DNE_0_v2.txt](https://github.com/twilio/twilio-chat-demo-ios/files/2075217/com.sendaride.carepartner_issue_99_crash_e5ff8148156c4bdbbc3f1411fefa09ce_DNE_0_v2.txt)
[com.sendaride.carepartner_issue_100_crash_624c6ab62ff747a1bfea478c3ebc0a2c_DNE_0_v2.txt](https://github.com/twilio/twilio-chat-demo-ios/files/2075218/com.sendaride.carepartner_issue_100_crash_624c6ab62ff747a1bfea478c3ebc0a2c_DNE_0_v2.txt)
[com.sendaride.carepartner_issue_101_crash_8ee2ac2bd58c4228ac4ba68d7e395182_DNE_0_v2.txt](https://github.com/twilio/twilio-chat-demo-ios/files/2075219/com.sendaride.carepartner_issue_101_crash_8ee2ac2bd58c4228ac4ba68d7e395182_DNE_0_v2.txt)

Regards
Siva Krishna.

**Comment by rbeiter** [comment]
Hello @perlasivakrishna ,
These are all related to a set of known issues we are working on.  You will notice that all of these stacktraces occur when the main thread is responding to `applicationWillTerminate`.  These crashes occur when the application is already being terminated by the operating system for inactivity or memory reasons and the shutdown within the Chat client does not have enough time to properly shutdown its resources.  This is a side-effect of the app already being terminated and not causing a crash on its own within your application.  We are working on some internal changes which 
will hopefully address this occurring in a future update.

Thank you,
Randy

**Comment by perlasivakrishna** [comment]
Hello @rbeiter 
Thanks for response. Waiting for updates.

**Comment by Gray-Wind** [comment]
We did a lot of fixes for proper shutdown, I believe it should be fixed. Open a new ticket if you still have crashes.
