### ISSUE TITLE
Local message cache

### ISSUE THREAD

**Issue by etown** [twilio/ip-demo-ios#43]
Is there a local cache of messages on the iOS client? It seems like it is hinted at in the documentation, but can you elaborate on synchronization?

Specifically, my use case is creating a client like most consumer chat applications(WhatsApp, Messenger, etc) 
The expectation is that when launching the app we can show the thread list with a snippet of the last message. Also, When going from the thread list into a thread view there should not be a async call needed to show the last page of messages(Although they may be out of sync depending on sync state). 

Ideally, in the case of the app launch the client could return the channel list from the last successful sync which we could use while the new sync is underway. That way, we could provide the optimal experience of showing the last message state instantly and update it if needed after the synchronization is complete. 

So my questions:
1) Is there an accessible persistent message cache which can be used before sync is complete?
2) If not, is there an internal one which means even if we have to block until synchronization is complete it will efficiently synchronize all channels and first page of messages?

Thank you!!

**Comment by Gray-Wind** [comment]
We have offline support in our roadmap, but I cannot give you any estimate.

**Comment by Gray-Wind** [comment]
I'm closing this ticked, will update #22 once we have offline support.
