### ISSUE TITLE
Issue with Using twilio in share extension

### ISSUE THREAD

**Issue by ankitappstreet** [twilio/ip-demo-ios#47]
### Description
We are building a chat app with a share extension. Initialising twilio chat client works fine with main app. But initialising twilio chat client within share  extension crashes the app with the following error : 

#### Crash logs 
```
2019-04-23 18:37:11.295780+0530 AthleteShareExtension[26045:943861] <<<<TwilioChatClient: 0x600003577800>>>> - [rtd] [DEBUG]        0x11b7fc5c0 | Chat-iOS | Logging initialized
2019-04-23 18:37:39.923417+0530 AthleteShareExtension[26045:943479] Task <3E5C354E-7306-49D6-A006-1E7833B64D3E>.<1> finished with error - code: -1001
2019-04-23 18:37:39.924353+0530 AthleteShareExtension[26045:943861] <<<<TwilioChatClient: 0x600003577800>>>> - [rtd] [FATAL]        0x11b7fc5c0 | Chat-iOS | Error instantiating client framework path.
2019-04-23 18:37:43.214026+0530 AthleteShareExtension[26045:943861] <<<<TwilioChatClient: 0x600003577800>>>> - [rtd] [DEBUG]        0x11b7fc5c0 | Chat-iOS | releasing chat client instance: <TwilioChatClient: 0x600003577800>
```

Sample code can be downloaded from dropbox. Links are given below. We have implemented twilio with and without cocoa pods.
-> With Pods:- https://www.dropbox.com/s/pf302ok7n5bjqvg/TwilioChat_Share_WithPod.zip?dl=0
-> Without Pods:- https://www.dropbox.com/s/96rikhb2dyvp5dj/TwilioChat_Share_WithoutPod.zip?dl=0

#### Reproduces how Often
Everytime when we try to instantiate twilio chat client in share extension.

#### Chat iOS SDK

Using TwilioChatClient (2.4.6)

#### iOS Version

iOS 11 & 12

**Comment by berkus** [comment]
SDK looks up the framework path inside the current main bundle via:
```
NSBundle *mainBundle = [NSBundle mainBundle];
NSString *chatFrameworkPath = [mainBundle pathForResource:@"TwilioChatClient" ofType:@"framework" inDirectory:@"Frameworks"];
```
if the framework is not found in the bundle, it will raise this error.

**Comment by berkus** [comment]
The `mainBundle` [is different when called from an extension](https://stackoverflow.com/questions/26189060/get-the-main-app-bundle-from-within-extension) - we will need to see how this can be fixed from within SDK.

As a workaround you could try bundling the framework to the extension directory.

**Comment by rohit-appstreet** [comment]
@berkus  we tried adding TwilioChatClient in both our targets (App and share extension) but we are still getting the same error. 
Also we are getting warnings while building 
```
ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/developer/Development/AppName-iOS/AppName/Pods/TwilioAccessManager/TwilioAccessManager.framework/TwilioAccessManager
ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/developer/Development/AppName-iOS/AppName/Pods/TwilioChatClient/TwilioChatClient.framework/TwilioChatClient
```

**Comment by ankitappstreet** [comment]
I have added the framework manually in both the Targets. Screenshots are attached. The issue is still same.

![Screenshot 2019-05-21 at 3 02 54 PM](https://user-images.githubusercontent.com/39150212/58085206-efa1f880-7bd9-11e9-9012-a0379fd6d763.png)
![Screenshot 2019-05-21 at 3 03 02 PM](https://user-images.githubusercontent.com/39150212/58085207-efa1f880-7bd9-11e9-8cf7-5229378f1184.png)

**Comment by berkus** [comment]
This might require fixing on our side, thanks for reporting. We will take a look!

**Comment by rohit-appstreet** [comment]
@berkus  can you pls share estimated time for this fix?

**Comment by berkus** [comment]
@rohit-appstreet we have no ETA at the moment, there are code quality updates coming up, after that I think we can look into this.

**Comment by Gray-Wind** [comment]
Ability to use Chat from extension has been added with version 2.6.1 of SDK.
