### ISSUE TITLE
Unread count and last message properties on a TCHChannel

### ISSUE THREAD

**Issue by s-gilroy** [twilio/ip-demo-ios#48]
### Description

Is there a way to get both the unread status of a channel and the body of the last message in a channel without making async calls `getUnconsumedMessagesCountWithCompletion:` and `messageWithIndex:completion:`? We are trying to replicate a UI similar to iMessage. Where each channel is shown in a list with the unread status and the last message in the channel showing before a user taps into a channel.

![image](https://user-images.githubusercontent.com/34253431/63121064-74da4680-bf58-11e9-8804-393f4cd25ca4.png)

The only way I can see this being possible is to make two async calls using the SDK for every single channel in the list. We could lazy load this as a user scrolls but its not a great experience. 

Do you have any suggestions? It would be ideal if these were properties on the TCHChannel itself ie channel.lastMessage or channel.hasUnread so I wouldn’t have to wait on async network calls for this data.

**Comment by Gray-Wind** [comment]
You could use
```objc
- (void)getLastMessagesWithCount:(NSUInteger)count
                      completion:(nonnull TCHMessagesCompletion)completion;
```
from `Channel.messages` and compare index with `lastConsumedMessageIndex` of `messages`, `lastConsumedMessageIndex` should be less for having unread messages.

**Comment by Gray-Wind** [comment]
Sorry, I misunderstood your question. You did everything correctly. Your way is only right way for now.

But in the future we have plans to add the offline storage and such task would be solved without network calls.

**Comment by Gray-Wind** [comment]
I'm closing this issue, as original question was answered. I'll keep #22 to track progress.
