### ISSUE TITLE
User unsubscribe() method not working as expected

### ISSUE THREAD

**Issue by lukluca** [twilio/ip-demo-ios#51]
### Description

Calling unsubscribe method on a subscribed user prevents that the same user can be subscribed again.
The next time the member.subscribedUser(completion) method is called the completion is never going to be triggered neither with an error state.
The issue is presented from version 2.4.8 until 2.6.2, which is the latest stable. We don't know if is present also in earlier version.

The same [issue](https://github.com/twilio/twilio-chat-demo-android/issues/106#issue-503459092) is present on Android Chat SDK.

### Steps to Reproduce

1. call member.subscribedUser(completion) and wait for success callback of this method.
2. call user.unsubscribe() on all the subscribed users (except the logged one).
3. go thru step 1 again but callback will no longer be triggered, neither success or error state.

#### Expected Behavior

We expect to be able to subscribe to the same user again after some time.

#### Chat iOS SDK

v2.6.2

#### iOS SDK Version

Tested on version 13.

**Comment by Gray-Wind** [comment]
Thank you, we will address this issue as soon as possible.

**Comment by Gray-Wind** [comment]
2.6.4 has been released with fix for this issue, so I'm closing this issue.
