### ISSUE TITLE
"Empty Credentials" in twilio debugger while initiating a call from iOS

### ISSUE THREAD

**Issue by yatindma** [twilio/ip-demo-ios#54]
I am trying to initiate a call from iOS then it's connecting for 2-3 sec and getting disconnected after that and in Twilio debugger we are getting "Empty Credentials", do you have nay idea regarding the same.

**Comment by Gray-Wind** [comment]
Please fill your bug report at https://github.com/twilio/video-quickstart-ios, https://github.com/twilio/twilio-video-app-ios or https://github.com/twilio/twilio-video-ios, as this repo is only about chat service.
